In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [79]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [78]:
import numpy as np
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [81]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [83]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points.shape

torch.Size([6])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [98]:
c = list(range(6))

d = 1*c
d.reverse()
c, d
d = torch.tensor(d)
print(d.shape)
d = d[None][None]
print(d.shape)

torch.Size([6])
torch.Size([1, 1, 6])


In [105]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [109]:
batch_t = torch.randn(2,3,5,5)
batch_t.shape
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape,  batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [117]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
print(batch_t.shape, unsqueezed_weights.shape)
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_t.sum(-3)

# batch_weights.shape, batch_t.shape, weights.shape, unsqueezed_weights.shape, img_gray_weighted.shape

torch.Size([2, 3, 5, 5]) torch.Size([3, 1, 1])


In [123]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted.shape

torch.Size([2, 5, 5])

In [139]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_named.shape

gray_named = (img_named*weights_aligned).sum('channels')


k = (img_named * img_weights).sum(-3)
k.shape, gray_named.shape

(torch.Size([5, 5]), torch.Size([5, 5]))

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [141]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])

In [146]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage().dtype

torch.float32

In [145]:
points_storage = points.storage()
points_storage.dtype

torch.float32

In [20]:
points.storage()[1]

1.0

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

In [25]:
points.stride()

(2, 1)

In [26]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [27]:
second_point.storage_offset()

2

In [28]:
second_point.stride()

(1,)

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [151]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [152]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [153]:
id(points.storage()) == id(points_t.storage())

False

In [154]:
points.stride()

(2, 1)

In [155]:
points_t.stride()

(1, 2)

In [157]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [158]:
transpose_t.shape

torch.Size([5, 4, 3])

In [159]:
some_t.stride()

(20, 5, 1)

In [160]:
transpose_t.stride()

(1, 5, 20)

In [167]:
points.is_contiguous()


True

In [162]:
points_t.is_contiguous()

False

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [43]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [44]:
points_t.stride()

(1, 2)

In [45]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t_cont.stride()

(3, 1)

In [47]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [49]:
short_points.dtype

torch.int16

In [50]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [51]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [52]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [53]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [54]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [55]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [57]:
points = torch.from_numpy(points_np)

In [184]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [185]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [186]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [188]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [195]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

dset

<Closed HDF5 dataset>

In [198]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

f['coords'], last_points

(<HDF5 dataset "coords": shape (3, 2), type "<f4">,
 array([[5., 3.],
        [2., 1.]], dtype=float32))

In [64]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [168]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [169]:
points_gpu = points.to(device='cuda')

In [181]:
points_gpu = points.to(device='cuda:0')

import numpy as np

poi = np.array(points_gpu.cpu())


poii = torch.tensor(poi)
poi, points_gpu.cpu().numpy(), poii

(array([[4., 1.],
        [5., 3.],
        [2., 1.]], dtype=float32),
 array([[4., 1.],
        [5., 3.],
        [2., 1.]], dtype=float32),
 tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]))

In [68]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [69]:
points_gpu = points_gpu + 4

In [70]:
points_cpu = points_gpu.to(device='cpu')

In [71]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [72]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [73]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [74]:
a = torch.ones(3, 2)

In [75]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [200]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [201]:
b = a.view(3,3)

In [202]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [208]:
c = b[1:, 1:]
c.storage(), c.size(), c.storage_offset(), c.stride()

( 0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
 torch.Size([2, 2]),
 4,
 (3, 1))

In [211]:
b ** 0.5, torch.sqrt(b)

(tensor([[0.0000, 1.0000, 1.4142],
         [1.7321, 2.0000, 2.2361],
         [2.4495, 2.6458, 2.8284]]),
 tensor([[0.0000, 1.0000, 1.4142],
         [1.7321, 2.0000, 2.2361],
         [2.4495, 2.6458, 2.8284]]))